### ISSUE TITLE
Create page link block

### ISSUE THREAD

**Issue by todaysday** [arturtamborski/notion-py#42]
Hi @arturtamborski 
Could you please advice me. Is any way to create page link block with py-noton?

**Comment by arturtamborski** [comment]
Hi!
TLDR: Unfortunately - no. You'll have to wait a bit for me to finish #32 

Longer answer:
Neither my fork nor the original repo has a pythonic representation of that particular notion block (type=`link_to_page`).
I will implement it along with every other basic/embed/media/upload block in #41 later in the development but first I have to finish fixing the lib to work again with defined smoke tests.

The block itself is representable in notion-py but it's recognized as a `PageBlock`, but all you can do is change the title of already existing link.

```
(Pdb) client = NotionClient(x)
(Pdb) page = os.environ['NOTION_PAGE_URL']
(Pdb) client.get_block(page)
<PageBlock (id='e7733878-...', title='smoke tests')>
(Pdb) x = client.get_block(page)
(Pdb) x
<PageBlock (id='e7733878-...', title='smoke tests')> # the page itself
(Pdb) x.children[0]
<PageBlock (id='e7733878-...', title='smoke tests')> # the link pointing at itself
(Pdb) x.children[0].title = 'nothing else'
(Pdb) x.children[0].title
'nothing else'
```

**Comment by todaysday** [comment]
Thank you very much for the answer. Nice workaround

**Comment by arturtamborski** [comment]
Hi, turns out I didn't fully understand how this all worked. notion.so represents LinkToPageBlock as an alias which was supported in the original repo and is supported in this repo as well, it's just that I didn't knew how to use it 😄 

Here's an example that should help you:

I have a space with two pages - "smoke tests" and "console".
```python3
import os
from notion.client import NotionClient

client = NotionClient(os.environ["NOTION_TOKEN_V2"])
page = client.get_block(os.environ["NOTION_PAGE_URL"])

console = client.get_block("https://www.notion.so/org/console-2a2f...5b6d")
page.children.add_alias(console)
```

and when I run it the page will look like so:
![image](https://user-images.githubusercontent.com/8676740/94156375-53000280-fe80-11ea-9526-dbb13f1bab3f.png)

but when I call `add_alias` a few more times... and with different page:
```python3
page.children.add_alias(console)
page.children.add_alias(console)
page.children.add_alias(food)
```

I get that:
![image](https://user-images.githubusercontent.com/8676740/94156597-8b9fdc00-fe80-11ea-8023-f979779f8669.png)


Notice that the console was _not_ added multiple times. I don't know yet why that happens. I can't add multiple links to the same page using notions gui as well so I guess it's some kind of limitation on their side.

Anyway, I believe that's a 'correct' way of adding a page link block using notion-py.

**Comment by todaysday** [comment]
Thanks
