### ISSUE TITLE
get_property() bug

### ISSUE THREAD

**Issue by ArtemErmulin** [arturtamborski/notion-py#70]
In the table block, when creating columns (properties), the column id can contain a dot symbol. For example `=f).` (i have this one, when i found bug).

In this case, when calling the `get_property()` method, `None` will be returned.

This happens because in the function `notion.utils.get_by_path()` the `path` is split by a dot:
```python
path = path.split(".")
```

**Comment by arturtamborski** [comment]
Whoa, I wonder how that one works on notion.so side, because to me it just sounds mad! A key in a dict with a mad dot in it! I guess they just went only with lists of keys.
Aaaanyway, I can't properly fix it from my side, I can only patch it so that it will kinda work for this case.

And sorry for late reply, I'm working on a fix for this one right now.

**Comment by ArtemErmulin** [comment]
Thanks for the answer!) I think this is not such a common bug, but I think it may suddenly appear. I also don't know how to create IDs for table columns, which adds a surprise effect to this bug.

**Comment by arturtamborski** [comment]
I think I fixed it in linked PR, though I was not able to generate real example with a dot in id, so this was not _not_ tested with notion. I still think it should fix your issue.

It would be great if you could test it again and confirm that the `get_by_path()` works.
In the meantime I'll do a patch release.

Thanks for this report and a great description (it really helped with fixing it!).

**Comment by arturtamborski** [comment]
Please try https://pypi.org/project/notion-py/0.0.8/ (latest one) and see if it solves the problem.

**Comment by ArtemErmulin** [comment]
Yeah, works great! Thanks for fix it!
